package com.gui;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Locale;

public class GUI_MainMenu implements ActionListener {
    JPanel pMainMenu;
    private JPanel pLeftHeader;
    private JLabel lblLogo;
    private JPanel pMenu;
    private JPanel pMain;
    private JPanel pRightHeader;
    private JButton btnHome;
    private JButton btnSelling;
    private JPanel pOption;
    private JComboBox cbbOption;
    private JButton btnProduct;
    private JButton btnPromotion;
    private JButton btnStatistic;
    private JButton btnStaff;
    private JButton btnGuideLine;
    private JButton btnLogout;
    private JButton btnCustomer;
    private CardLayout cardLayout;

    private void createUIComponents() {
        // TODO: place custom component creation code here


    }


    public GUI_MainMenu() {

        cardLayout = (CardLayout) pMain.getLayout();


        btnHome.addActionListener(this);
        btnSelling.addActionListener(this);
        btnProduct.addActionListener(this);
        btnPromotion.addActionListener(this);
        btnStatistic.addActionListener(this);
        btnStaff.addActionListener(this);
        btnGuideLine.addActionListener(this);
        btnLogout.addActionListener(this);
        btnCustomer.addActionListener(this);


        TAB_Dashboard dashboard = new TAB_Dashboard();
        TAB_Selling sales = new TAB_Selling();
        TAB_Promotion promotion = new TAB_Promotion();
        TAB_Statistic statistic = new TAB_Statistic();
        TAB_Product product = new TAB_Product();
        TAB_Staff staff = new TAB_Staff();
        TAB_Customer customer = new TAB_Customer();

        pMain.add(dashboard.pDashboard, "dashboard");
        pMain.add(sales.pSelling, "selling");
        pMain.add(promotion, "promotion");
        pMain.add(statistic.pStatistic, "statistic");
        pMain.add(product.pProduct, "product");
        pMain.add(staff.pStaff, "staff");
        pMain.add(customer.pCustomer, "customer");


        setActiveButton(btnHome);
        cardLayout.show(pMain, "dashboard");


    }

    @Override
    public void actionPerformed(ActionEvent e) {
        Object src = e.getSource();

        if (src == btnHome) {
            setActiveButton(btnHome);
            cardLayout.show(pMain, "dashboard");
        } else if (src == btnSelling) {
            setActiveButton(btnSelling);
            cardLayout.show(pMain, "selling");

        } else if (src == btnProduct) {
            setActiveButton(btnProduct);
            cardLayout.show(pMain, "product");

        } else if (src == btnPromotion) {
            setActiveButton(btnPromotion);
            cardLayout.show(pMain, "promotion");

        } else if (src == btnStatistic) {
            setActiveButton(btnStatistic);
            cardLayout.show(pMain, "statistic");

        } else if (src == btnStaff) {
            setActiveButton(btnStaff);
            cardLayout.show(pMain, "staff");

        } else if (src == btnGuideLine) {
            setActiveButton(btnGuideLine);

        } else if (src == btnLogout) {
            int choice = JOptionPane.showConfirmDialog(pMainMenu, "Bạn có chắc chắn muốn đăng xuất?", "Xác nhận đăng xuất", JOptionPane.YES_NO_OPTION);
            if (choice == JOptionPane.YES_OPTION) {
                // Close current main menu window
                JFrame topFrame = (JFrame) SwingUtilities.getWindowAncestor(pMainMenu);
                topFrame.dispose();

                // Open login window
                JFrame loginFrame = new JFrame("MediWOW - Đăng nhập");
                loginFrame.setContentPane(new GUI_Login().pLogin);
                loginFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                loginFrame.setSize(1080, 600);
                loginFrame.setLocationRelativeTo(null);
                loginFrame.setResizable(false);
                loginFrame.setVisible(true);
            }

        } else if (src == btnCustomer) {
            setActiveButton(btnCustomer);
            cardLayout.show(pMain, "customer");

        }

    }

    private void setActiveButton(JButton activeButton) {

        for (Component comp : pMenu.getComponents()) {
            if (comp instanceof JButton) {
                JButton btn = (JButton) comp;
                btn.setBackground(UIManager.getColor("Button.background"));
            }
        }

        activeButton.setBackground(new Color(0, 204, 203));

    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        pMainMenu = new JPanel();
        pMainMenu.setLayout(new GridBagLayout());
        pMainMenu.setBackground(new Color(-2236963));
        pMainMenu.setPreferredSize(new Dimension(1920, 1080));
        pLeftHeader = new JPanel();
        pLeftHeader.setLayout(new BorderLayout(0, 0));
        pLeftHeader.setBackground(new Color(-16724789));
        pLeftHeader.setForeground(new Color(-16012317));
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.BOTH;
        pMainMenu.add(pLeftHeader, gbc);
        lblLogo = new JLabel();
        lblLogo.setBackground(new Color(-2236963));
        lblLogo.setIcon(new ImageIcon(getClass().getResource("/images/logo.png")));
        lblLogo.setText("");
        pLeftHeader.add(lblLogo, BorderLayout.CENTER);
        pMenu = new JPanel();
        pMenu.setLayout(new GridBagLayout());
        pMenu.setAlignmentY(0.5f);
        pMenu.setBackground(new Color(-2236963));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.BOTH;
        pMainMenu.add(pMenu, gbc);
        btnHome = new JButton();
        btnHome.setAlignmentY(0.5f);
        btnHome.setAutoscrolls(false);
        btnHome.setBackground(new Color(-1));
        btnHome.setBorderPainted(true);
        btnHome.setContentAreaFilled(true);
        btnHome.setDefaultCapable(true);
        btnHome.setDoubleBuffered(false);
        btnHome.setEnabled(true);
        btnHome.setFocusCycleRoot(false);
        btnHome.setFocusPainted(true);
        Font btnHomeFont = this.$$$getFont$$$("Segoe UI", Font.BOLD, 16, btnHome.getFont());
        if (btnHomeFont != null) btnHome.setFont(btnHomeFont);
        btnHome.setForeground(new Color(-16027943));
        btnHome.setHideActionText(false);
        btnHome.setHorizontalAlignment(2);
        btnHome.setIcon(new ImageIcon(getClass().getResource("/icons/btn_home.png")));
        btnHome.setIconTextGap(10);
        btnHome.setMargin(new Insets(0, 10, 0, 0));
        btnHome.setPreferredSize(new Dimension(180, 50));
        btnHome.setRolloverEnabled(true);
        btnHome.setSelected(false);
        btnHome.setText("Màn hình chính");
        btnHome.setToolTipText("Nhấp để quay về trang chủ");
        btnHome.putClientProperty("hideActionText", Boolean.FALSE);
        btnHome.putClientProperty("html.disable", Boolean.FALSE);
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(0, 0, 20, 0);
        pMenu.add(btnHome, gbc);
        btnSelling = new JButton();
        btnSelling.setAlignmentY(0.5f);
        btnSelling.setAutoscrolls(false);
        btnSelling.setBackground(new Color(-1));
        btnSelling.setBorderPainted(true);
        btnSelling.setContentAreaFilled(true);
        btnSelling.setDefaultCapable(true);
        btnSelling.setDoubleBuffered(false);
        btnSelling.setEnabled(true);
        btnSelling.setFocusCycleRoot(false);
        btnSelling.setFocusPainted(true);
        Font btnSellingFont = this.$$$getFont$$$("Segoe UI", Font.BOLD, 16, btnSelling.getFont());
        if (btnSellingFont != null) btnSelling.setFont(btnSellingFont);
        btnSelling.setForeground(new Color(-16027943));
        btnSelling.setHideActionText(false);
        btnSelling.setHorizontalAlignment(2);
        btnSelling.setIcon(new ImageIcon(getClass().getResource("/icons/btn_selling.png")));
        btnSelling.setIconTextGap(10);
        btnSelling.setMargin(new Insets(0, 10, 0, 0));
        btnSelling.setPreferredSize(new Dimension(150, 50));
        btnSelling.setRolloverEnabled(true);
        btnSelling.setSelected(false);
        btnSelling.setText("Bán hàng");
        btnSelling.setToolTipText("Nhấp vào để bắt đầu bán hàng");
        btnSelling.putClientProperty("hideActionText", Boolean.FALSE);
        btnSelling.putClientProperty("html.disable", Boolean.FALSE);
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(0, 0, 20, 0);
        pMenu.add(btnSelling, gbc);
        btnProduct = new JButton();
        btnProduct.setAlignmentY(0.5f);
        btnProduct.setAutoscrolls(false);
        btnProduct.setBackground(new Color(-1));
        btnProduct.setBorderPainted(true);
        btnProduct.setContentAreaFilled(true);
        btnProduct.setDefaultCapable(true);
        btnProduct.setDoubleBuffered(false);
        btnProduct.setEnabled(true);
        btnProduct.setFocusCycleRoot(false);
        btnProduct.setFocusPainted(true);
        Font btnProductFont = this.$$$getFont$$$("Segoe UI", Font.BOLD, 16, btnProduct.getFont());
        if (btnProductFont != null) btnProduct.setFont(btnProductFont);
        btnProduct.setForeground(new Color(-16027943));
        btnProduct.setHideActionText(false);
        btnProduct.setHorizontalAlignment(2);
        btnProduct.setIcon(new ImageIcon(getClass().getResource("/icons/btn_product.png")));
        btnProduct.setIconTextGap(10);
        btnProduct.setMargin(new Insets(0, 10, 0, 0));
        btnProduct.setPreferredSize(new Dimension(150, 50));
        btnProduct.setRolloverEnabled(true);
        btnProduct.setSelected(false);
        btnProduct.setText("Sản phẩm");
        btnProduct.setToolTipText("Nhấp để quản lý sản phẩm");
        btnProduct.putClientProperty("hideActionText", Boolean.FALSE);
        btnProduct.putClientProperty("html.disable", Boolean.FALSE);
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(0, 0, 20, 0);
        pMenu.add(btnProduct, gbc);
        btnPromotion = new JButton();
        btnPromotion.setAlignmentY(0.5f);
        btnPromotion.setAutoscrolls(false);
        btnPromotion.setBackground(new Color(-1));
        btnPromotion.setBorderPainted(true);
        btnPromotion.setContentAreaFilled(true);
        btnPromotion.setDefaultCapable(true);
        btnPromotion.setDoubleBuffered(false);
        btnPromotion.setEnabled(true);
        btnPromotion.setFocusCycleRoot(false);
        btnPromotion.setFocusPainted(true);
        Font btnPromotionFont = this.$$$getFont$$$("Segoe UI", Font.BOLD, 16, btnPromotion.getFont());
        if (btnPromotionFont != null) btnPromotion.setFont(btnPromotionFont);
        btnPromotion.setForeground(new Color(-16027943));
        btnPromotion.setHideActionText(false);
        btnPromotion.setHorizontalAlignment(2);
        btnPromotion.setIcon(new ImageIcon(getClass().getResource("/icons/btn_promotion.png")));
        btnPromotion.setIconTextGap(10);
        btnPromotion.setMargin(new Insets(0, 10, 0, 0));
        btnPromotion.setPreferredSize(new Dimension(150, 50));
        btnPromotion.setRolloverEnabled(true);
        btnPromotion.setSelected(false);
        btnPromotion.setText("Khuyến mại");
        btnPromotion.setToolTipText("Nhấp vào để quản lý khuyến mại");
        btnPromotion.putClientProperty("hideActionText", Boolean.FALSE);
        btnPromotion.putClientProperty("html.disable", Boolean.FALSE);
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(0, 0, 20, 0);
        pMenu.add(btnPromotion, gbc);
        btnStatistic = new JButton();
        btnStatistic.setAlignmentY(0.5f);
        btnStatistic.setAutoscrolls(false);
        btnStatistic.setBackground(new Color(-1));
        btnStatistic.setBorderPainted(true);
        btnStatistic.setContentAreaFilled(true);
        btnStatistic.setDefaultCapable(true);
        btnStatistic.setDoubleBuffered(false);
        btnStatistic.setEnabled(true);
        btnStatistic.setFocusCycleRoot(false);
        btnStatistic.setFocusPainted(true);
        Font btnStatisticFont = this.$$$getFont$$$("Segoe UI", Font.BOLD, 16, btnStatistic.getFont());
        if (btnStatisticFont != null) btnStatistic.setFont(btnStatisticFont);
        btnStatistic.setForeground(new Color(-16027943));
        btnStatistic.setHideActionText(false);
        btnStatistic.setHorizontalAlignment(2);
        btnStatistic.setIcon(new ImageIcon(getClass().getResource("/icons/btn_statistic.png")));
        btnStatistic.setIconTextGap(10);
        btnStatistic.setMargin(new Insets(0, 10, 0, 0));
        btnStatistic.setPreferredSize(new Dimension(150, 50));
        btnStatistic.setRolloverEnabled(true);
        btnStatistic.setSelected(false);
        btnStatistic.setText("Thống kê");
        btnStatistic.setToolTipText("Nhấp vào để bắt đầu thống kê");
        btnStatistic.putClientProperty("hideActionText", Boolean.FALSE);
        btnStatistic.putClientProperty("html.disable", Boolean.FALSE);
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(0, 0, 20, 0);
        pMenu.add(btnStatistic, gbc);
        btnStaff = new JButton();
        btnStaff.setAlignmentY(0.5f);
        btnStaff.setAutoscrolls(false);
        btnStaff.setBackground(new Color(-1));
        btnStaff.setBorderPainted(true);
        btnStaff.setContentAreaFilled(true);
        btnStaff.setDefaultCapable(true);
        btnStaff.setDoubleBuffered(false);
        btnStaff.setEnabled(true);
        btnStaff.setFocusCycleRoot(false);
        btnStaff.setFocusPainted(true);
        Font btnStaffFont = this.$$$getFont$$$("Segoe UI", Font.BOLD, 16, btnStaff.getFont());
        if (btnStaffFont != null) btnStaff.setFont(btnStaffFont);
        btnStaff.setForeground(new Color(-16027943));
        btnStaff.setHideActionText(false);
        btnStaff.setHorizontalAlignment(2);
        btnStaff.setIcon(new ImageIcon(getClass().getResource("/icons/btn_staff.png")));
        btnStaff.setIconTextGap(10);
        btnStaff.setMargin(new Insets(0, 10, 0, 0));
        btnStaff.setPreferredSize(new Dimension(150, 50));
        btnStaff.setRolloverEnabled(true);
        btnStaff.setSelected(false);
        btnStaff.setText("Nhân viên");
        btnStaff.setToolTipText("Nhấp vào để quản lý thông tin nhân viên");
        btnStaff.putClientProperty("hideActionText", Boolean.FALSE);
        btnStaff.putClientProperty("html.disable", Boolean.FALSE);
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 5;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(0, 0, 20, 0);
        pMenu.add(btnStaff, gbc);
        btnGuideLine = new JButton();
        btnGuideLine.setAlignmentY(0.5f);
        btnGuideLine.setAutoscrolls(false);
        btnGuideLine.setBackground(new Color(-1));
        btnGuideLine.setBorderPainted(true);
        btnGuideLine.setContentAreaFilled(true);
        btnGuideLine.setDefaultCapable(true);
        btnGuideLine.setDoubleBuffered(false);
        btnGuideLine.setEnabled(true);
        btnGuideLine.setFocusCycleRoot(false);
        btnGuideLine.setFocusPainted(true);
        Font btnGuideLineFont = this.$$$getFont$$$("Segoe UI", Font.BOLD, 16, btnGuideLine.getFont());
        if (btnGuideLineFont != null) btnGuideLine.setFont(btnGuideLineFont);
        btnGuideLine.setForeground(new Color(-16027943));
        btnGuideLine.setHideActionText(false);
        btnGuideLine.setHorizontalAlignment(2);
        btnGuideLine.setIcon(new ImageIcon(getClass().getResource("/icons/btn_help.png")));
        btnGuideLine.setIconTextGap(10);
        btnGuideLine.setMargin(new Insets(0, 10, 0, 0));
        btnGuideLine.setPreferredSize(new Dimension(150, 50));
        btnGuideLine.setRolloverEnabled(true);
        btnGuideLine.setSelected(false);
        btnGuideLine.setText("Hướng dẫn");
        btnGuideLine.setToolTipText("Nhấp vào để xem hướng dẫn");
        btnGuideLine.putClientProperty("hideActionText", Boolean.FALSE);
        btnGuideLine.putClientProperty("html.disable", Boolean.FALSE);
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 7;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(0, 0, 50, 0);
        pMenu.add(btnGuideLine, gbc);
        btnLogout = new JButton();
        btnLogout.setAlignmentY(0.5f);
        btnLogout.setAutoscrolls(false);
        btnLogout.setBackground(new Color(-1));
        btnLogout.setBorderPainted(true);
        btnLogout.setContentAreaFilled(true);
        btnLogout.setDefaultCapable(true);
        btnLogout.setDoubleBuffered(false);
        btnLogout.setEnabled(true);
        btnLogout.setFocusCycleRoot(false);
        btnLogout.setFocusPainted(true);
        Font btnLogoutFont = this.$$$getFont$$$("Segoe UI", Font.BOLD, 16, btnLogout.getFont());
        if (btnLogoutFont != null) btnLogout.setFont(btnLogoutFont);
        btnLogout.setForeground(new Color(-16027943));
        btnLogout.setHideActionText(false);
        btnLogout.setHorizontalAlignment(2);
        btnLogout.setIcon(new ImageIcon(getClass().getResource("/icons/btn_logout.png")));
        btnLogout.setIconTextGap(10);
        btnLogout.setMargin(new Insets(0, 10, 0, 0));
        btnLogout.setPreferredSize(new Dimension(150, 50));
        btnLogout.setRolloverEnabled(true);
        btnLogout.setSelected(false);
        btnLogout.setText("Đăng xuất");
        btnLogout.setToolTipText("Nhấp vào để đăng xuất");
        btnLogout.putClientProperty("hideActionText", Boolean.FALSE);
        btnLogout.putClientProperty("html.disable", Boolean.FALSE);
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 8;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(150, 0, 20, 0);
        pMenu.add(btnLogout, gbc);
        btnCustomer = new JButton();
        btnCustomer.setAlignmentY(0.5f);
        btnCustomer.setAutoscrolls(false);
        btnCustomer.setBackground(new Color(-1));
        btnCustomer.setBorderPainted(true);
        btnCustomer.setContentAreaFilled(true);
        btnCustomer.setDefaultCapable(true);
        btnCustomer.setDoubleBuffered(false);
        btnCustomer.setEnabled(true);
        btnCustomer.setFocusCycleRoot(false);
        btnCustomer.setFocusPainted(true);
        Font btnCustomerFont = this.$$$getFont$$$("Segoe UI", Font.BOLD, 16, btnCustomer.getFont());
        if (btnCustomerFont != null) btnCustomer.setFont(btnCustomerFont);
        btnCustomer.setForeground(new Color(-16027943));
        btnCustomer.setHideActionText(false);
        btnCustomer.setHorizontalAlignment(2);
        btnCustomer.setIcon(new ImageIcon(getClass().getResource("/icons/btn_customer.png")));
        btnCustomer.setIconTextGap(10);
        btnCustomer.setMargin(new Insets(0, 10, 0, 0));
        btnCustomer.setPreferredSize(new Dimension(150, 50));
        btnCustomer.setRolloverEnabled(true);
        btnCustomer.setSelected(false);
        btnCustomer.setText("Khách hàng");
        btnCustomer.setToolTipText("Nhấp vào để quản lý thông tin khách hàng");
        btnCustomer.putClientProperty("hideActionText", Boolean.FALSE);
        btnCustomer.putClientProperty("html.disable", Boolean.FALSE);
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 6;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(0, 0, 20, 0);
        pMenu.add(btnCustomer, gbc);
        pMain = new JPanel();
        pMain.setLayout(new CardLayout(0, 0));
        pMain.setBackground(new Color(-2236963));
        pMain.setEnabled(true);
        pMain.putClientProperty("html.disable", Boolean.FALSE);
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.weightx = 10.0;
        gbc.weighty = 100.0;
        gbc.fill = GridBagConstraints.BOTH;
        pMainMenu.add(pMain, gbc);
        final JScrollPane scrollPane1 = new JScrollPane();
        pMain.add(scrollPane1, "Card1");
        pRightHeader = new JPanel();
        pRightHeader.setLayout(new BorderLayout(0, 0));
        pRightHeader.setBackground(new Color(-16724789));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.BOTH;
        pMainMenu.add(pRightHeader, gbc);
        pOption = new JPanel();
        pOption.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 50), -1, 30));
        pOption.setBackground(new Color(-16724789));
        pRightHeader.add(pOption, BorderLayout.EAST);
        cbbOption = new JComboBox();
        cbbOption.setAlignmentX(0.5f);
        cbbOption.setAlignmentY(0.5f);
        cbbOption.setBackground(new Color(-1));
        cbbOption.setEditable(false);
        cbbOption.setEnabled(true);
        Font cbbOptionFont = this.$$$getFont$$$(null, -1, 16, cbbOption.getFont());
        if (cbbOptionFont != null) cbbOption.setFont(cbbOptionFont);
        cbbOption.setForeground(new Color(-16012317));
        final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
        defaultComboBoxModel1.addElement("Xin chào, Tô Thanh Hậu");
        cbbOption.setModel(defaultComboBoxModel1);
        pOption.add(cbbOption, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return pMainMenu;
    }


}
