package com.gui;

import javax.swing.*;
import java.awt.*;

public class GUI_Login {
    private JButton btnLogin;
    public JPanel panel1;


    public GUI_Login() {
        btnLogin.addActionListener(e -> handleLogin());
    }

    private void handleLogin() {
        openMainMenu();
    }

    private void openMainMenu() {
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(panel1);
        frame.dispose();


        JFrame mainMenuFrame = new JFrame("MediWOW - Trang chủ");
        mainMenuFrame.setContentPane(new GUI_MainMenu().pMainMenu);
        mainMenuFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        mainMenuFrame.setLocationRelativeTo(null);
        mainMenuFrame.setVisible(true);
        mainMenuFrame.setExtendedState(JFrame.MAXIMIZED_BOTH);

    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        btnLogin = new JButton();
        btnLogin.setText("Button");
        panel1.add(btnLogin, BorderLayout.SOUTH);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}
