package com.gui;

import javax.swing.*;
import java.awt.*;

public class TAB_Promotion {
    JPanel pPromotion;
    private JButton btnDelete;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        pPromotion = new JPanel();
        pPromotion.setLayout(new BorderLayout(0, 0));
        pPromotion.setBackground(new Color(-2236963));
        btnDelete = new JButton();
        btnDelete.setText("Khôi");
        pPromotion.add(btnDelete, BorderLayout.CENTER);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return pPromotion;
    }
}
