package com.gui;

import javax.swing.*;
import java.awt.*;

public class TAB_Customer {
    JPanel pCustomer;
    private JButton kháchHàngButton;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        pCustomer = new JPanel();
        pCustomer.setLayout(new BorderLayout(0, 0));
        kháchHàngButton = new JButton();
        kháchHàngButton.setText("Khách hàng");
        pCustomer.add(kháchHàngButton, BorderLayout.CENTER);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return pCustomer;
    }
}
