package com.gui;

import javax.swing.*;
import java.awt.*;

public class TAB_Dashboard {
    JPanel pDashboard;
    private JButton pDelete;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        pDashboard = new JPanel();
        pDashboard.setLayout(new BorderLayout(0, 0));
        pDelete = new JButton();
        pDelete.setText("Hậu");
        pDashboard.add(pDelete, BorderLayout.CENTER);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return pDashboard;
    }
}
