package com.gui;

import javax.swing.*;
import java.awt.*;

public class TAB_Selling {
    JPanel pSelling;
    private JLabel lblDelete;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        pSelling = new JPanel();
        pSelling.setLayout(new BorderLayout(0, 0));
        lblDelete = new JLabel();
        lblDelete.setText("Trụ - Bán hàng");
        pSelling.add(lblDelete, BorderLayout.CENTER);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return pSelling;
    }

}
