package com.gui;

import javax.swing.*;
import java.awt.*;

public class TAB_Statistic {
    JPanel pStatistic;
    private JButton thốngKêButton;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        pStatistic = new JPanel();
        pStatistic.setLayout(new BorderLayout(0, 0));
        pStatistic.setBackground(new Color(-2236963));
        thốngKêButton = new JButton();
        thốngKêButton.setText("Thống kê");
        pStatistic.add(thốngKêButton, BorderLayout.CENTER);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return pStatistic;
    }
}
