package com.gui;

import javax.swing.*;
import java.awt.*;

public class TAB_Staff {
    JPanel pStaff;
    private JButton btnTest;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        pStaff = new JPanel();
        pStaff.setLayout(new BorderLayout(0, 0));
        btnTest = new JButton();
        btnTest.setText("Nhân viên");
        pStaff.add(btnTest, BorderLayout.CENTER);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return pStaff;
    }
}
