package com.gui;

import javax.swing.*;
import java.awt.*;

public class TAB_Dashboard {
    JPanel pDashboard;
    private JButton btnDelete;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        pDashboard = new JPanel();
        pDashboard.setLayout(new GridBagLayout());
        pDashboard.setBackground(new Color(-2236963));
        btnDelete = new JButton();
        btnDelete.setText("Dashboard");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        pDashboard.add(btnDelete, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return pDashboard;
    }

}
