package com.gui;

import javax.swing.*;
import java.awt.*;

public class TAB_Product {
    JPanel pProduct;
    private JButton btnTest;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        pProduct = new JPanel();
        pProduct.setLayout(new BorderLayout(0, 0));
        pProduct.setBackground(new Color(-2236963));
        pProduct.setForeground(new Color(-2236963));
        btnTest = new JButton();
        btnTest.setText("Minh - Sản phẩm");
        pProduct.add(btnTest, BorderLayout.CENTER);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return pProduct;
    }

}
